services:
  - type: web
    name: referral-system
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn referral_system.wsgi:application
    preDeployCommand: python manage.py migrate