# Generated by Django 4.2.23 on 2025-07-25 07:45

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16, unique=True)),
                ('invite_code', models.CharField(default=api.utils.generate_invite_code, max_length=6, unique=True)),
                ('used_invite_code', models.CharField(blank=True, default=None, max_length=6, null=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('phone',),
                'default_related_name': 'users',
            },
        ),
    ]
